# Generated by Django 4.2.6 on 2023-12-04 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='athletes.category', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_on'], name='athletes_co_created_39099d_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['time_update'], name='athletes_at_time_up_955091_idx'),
        ),
    ]
